workspace = { members = ["libscoutnet", "scoutnetpy"] }
[package]
name = "scoutnet"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "*", features = ["derive"]}
libscoutnet = { path = "./libscoutnet/"}
